language: node_js
node_js:
  - node

dist: bionic
sudo: required

notifications:
  email:
    recipients:
      - e0686302@u.nus.edu
    on_success: always
    on_failure: always
branches:
  only:
   - development
before_script:
  - npm install -g @angular/cli
  
script:
  #- ng build --prod --base-href https://atee12.github.io/bitcoin-order-app/
  - ng build --prod --base-href https://github.com/atee12/bitcoin-order-app.git/
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/bitcoin
  edge: true
  on:
    branch: development